Lit utilities lists
haarsh24/lit-ui pull request #7
Opened 2022-02-07 17:19 UTC by haarsh24

1. Added typography and lists

2022-02-07 17:59 UTC, tushargoyal812 requested changes
everything is good you just need to take care of indentation.

2022-02-07 17:59 UTC, tushargoyal812 commented on components/components.html
> +
remove unnecessary space

2022-02-07 17:59 UTC, tushargoyal812 commented on components/lists.css
> +.lists-item-stacked{
add space before { this important for indentation.

2022-02-07 17:59 UTC, tushargoyal812 commented on components/utlis.css
> +
also here remove unnecessary space from here

2022-02-08 17:39 UTC, xii-vi commented on components/lists.css
> +    color:var(--black);
use --white-color instead of only white

2022-02-08 17:40 UTC, xii-vi approved these changes
Just a tiny suggestion, rest is fine.
You can merge.

2022-02-08 17:43 UTC, merged